/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Yam
 */
public class Checkings extends javax.swing.JFrame {

    /**
     * Creates new form Checkings
     */
    public String username;
    public Checkings() {
        initComponents();
    }
    public Checkings(String para){
        this.username = para;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deposit_amount = new javax.swing.JTextField();
        withdraw_amount = new javax.swing.JTextField();
        deposit = new javax.swing.JButton();
        withdraw = new javax.swing.JButton();
        greetings = new javax.swing.JLabel();
        BackToOptions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deposit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deposit.setText("Deposit");
        deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionPerformed(evt);
            }
        });

        withdraw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        withdraw.setText("Withdraw");
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });

        greetings.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        greetings.setText("Welcome: "+ username );

        BackToOptions.setForeground(new java.awt.Color(0, 0, 255));
        BackToOptions.setText("Back to Account Options");
        BackToOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackToOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackToOptionsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deposit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(greetings, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BackToOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(withdraw_amount, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(withdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(greetings, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deposit, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(deposit_amount))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(withdraw_amount, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(withdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(BackToOptions)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
        int deposit = -1;
        try {
            deposit = Integer.parseInt(deposit_amount.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid number");
        }
        if (deposit < 0) {
            JOptionPane.showMessageDialog(null, "Please enter valid number");
        } else {
            AccountController accCtrl = new AccountController();
            Account acc = accCtrl.readAccount(username);
            acc.addCheckingBalance(deposit);
            accCtrl.writeAccount(acc);
            JOptionPane.showMessageDialog(null, "Succesfully deposited " + deposit_amount.getText());
        }
    }//GEN-LAST:event_depositActionPerformed

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed
        int withdrawal = -1;
        try {
            withdrawal = Integer.parseInt(withdraw_amount.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid number");
        }

        if(withdrawal < 0)
        {
            JOptionPane.showMessageDialog(null, "Please enter valid number");
        }
        else {
            AccountController accCtrl = new AccountController();
            Account acc = accCtrl.readAccount(username);
            if(withdrawal < acc.getCheckingBalance()){
                acc.subtractCheckingBalance(withdrawal);
                accCtrl.writeAccount(acc);
                JOptionPane.showMessageDialog(null, "Succesfully withdrew");
            } else {
                JOptionPane.showMessageDialog(null, "Can't withdraw more than balance");
            }
        }
    }//GEN-LAST:event_withdrawActionPerformed

    private void BackToOptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackToOptionsMouseClicked
        AccountOptions aOpt = new AccountOptions(username);
                aOpt.setVisible(true);
                aOpt.pack();
                aOpt.setLocationRelativeTo(null);
                aOpt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
    }//GEN-LAST:event_BackToOptionsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackToOptions;
    private javax.swing.JButton deposit;
    private javax.swing.JTextField deposit_amount;
    private javax.swing.JLabel greetings;
    private javax.swing.JButton withdraw;
    private javax.swing.JTextField withdraw_amount;
    // End of variables declaration//GEN-END:variables
}
